name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "running tests..."

build:
  stage: build
  script: echo "building..."
  jobs:
    environment:
      name: dev
    build:
      runs-on: ubuntu-latest
      env:
        POSTGRES_USER: ${{secrets.POSTGRES_USER}}
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      steps:
        - uses: actions/checkout@v2
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag tasqr-db:latest
  
  deploy:
    stage: deploy
    script: echo "deploying..."
